### ISSUE TITLE
Should-Do Items

### ISSUE THREAD

**Issue by DanVanAtta** [DanVanAtta/wnc-supply-sites#11]
- Should-DO: investigate duplicated data in AirTable
- Should-DO: hide phone numbers on WSS for everyone except logged in users
- Should-DO: add to site contact management page {email, point of contact name}
- Should-DO: add note on inventory page that R4 inventory system is triggered by status updates
- Should-Do:  nightly sync of site info from AirTable to WSS
- Should-Do: show needs requests to logged in users on site detail page

**Comment by DanielThaumazo** [comment]
Splitting
