### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DanVanAtta** [DanVanAtta/wnc-supply-sites#12]
- TODO: (Data Quality) mark non-contacted sites with no inventory updates as inactive, consider deleting from DB
- TODO: (UX) add item need status to site-detail page
- TODO: (UX) add link for logged-in users on detail page to inventory management page
- TODO: (UX) filtering of items by category on search & inventory managemenet pages
- TODO: (UX) on inventory management page, for diabled items, enable items if the disabled radio buttons are selected
- TODO: (UX) CSS tweaks for mobile UX, verify all looks good on mobile
- TODO: TN support --> add TN counties to DB, change 'state' selection to a drop down for NC & TN only, change county list dynamically if state is updated
- TODO: (Ops) alarming/monitoring, enable springboot actuator + pagerduty to send pages on error rate
- TODO: (SEO) add robots.txt page

**Comment by DanielThaumazo** [comment]
Splitting
