### ISSUE TITLE
Adding new items resets inventory changes

### ISSUE THREAD

**Issue by DanVanAtta** [DanVanAtta/wnc-supply-sites#39]
Repro:
- site management
- inventory management
- update inventory items (need status, check/uncheck items)
- add an item

Notice:
- inventory updates are reset

Expected
- inventory updates should remain as-was on the UI

Notes:
- the inventory updates are not reverted, just the UI is reverted.

**Comment by colormethanh** [comment]
Using "element += newItemRowHtml" reconstructs all child elements and removes any dynamic states such as the .checked and .disabled values. To preserve these values we should use element.insertAdjacentHTML.
